version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    restart: always
    environment:
      - NODE_ENV=production
    expose:
      - "8080"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
